### ISSUE TITLE
埋点系统几天未运行,执行npm run table_config报错

### ISSUE THREAD

**Issue by reed0214** [a597873885/webfunny_event#2]
埋点系统几天未运行,现在需要创建新的event相关表,但是执行**npm run table_config**,报错,提示 **Table 'webfunny_db.project' doesn't exist**,
查看数据库,确实不存在该表
![微信截图_20211129110552](https://user-images.githubusercontent.com/13160124/143803212-ccff6b09-5568-4f65-939c-6d5bfb130dd2.png)
![微信截图_20211129111246](https://user-images.githubusercontent.com/13160124/143803135-66ba660a-1f0a-40d3-be3e-4cf997083cd3.png)

通过新建相关event的sdk,可以正常建表
![微信截图_20211129112616](https://user-images.githubusercontent.com/13160124/143804077-cd687b2f-7841-4a62-8815-114ca78832c8.png)
![QQ截图20211129112243](https://user-images.githubusercontent.com/13160124/143803768-daf7dcb9-8c64-43c7-abfb-a96158caa8d5.png)

**Comment by yuyuleilei** [comment]
你好

**Comment by yuyuleilei** [comment]
npm run table_config命令目前还不支持埋点系统的创建表，后期我们考虑加上执行命令来创建表。
目前创建未生成的表有两种方式：
1、程序每天凌晨零点会自动创建今天和明天的表
2、新建或者更新sdk会自动创建今天和明天的表

**Comment by reed0214** [comment]
> npm run table_config命令目前还不支持埋点系统的创建表，后期我们考虑加上执行命令来创建表。 目前创建未生成的表有两种方式： 1、程序每天凌晨零点会自动创建今天和明天的表 2、更新sdk会自动创建今天和明天的表

那如果是昨天的表没有创建的话,就只能自己手动在数据库里面建表了么,

**Comment by yuyuleilei** [comment]
上报数据都是当天上报的，上报数据入库当天的表里面，今天在创建昨天的表就没有意义了啊

**Comment by reed0214** [comment]
> 上报数据都是当天上报的，上报数据入库当天的表里面，今天在创建昨天的表就没有意义了啊

确实,反正不存在默认就为0.只是日志会多一个缺少表的报错,也没啥影响,谢谢解答了,期待后期版本的支持

**Comment by yuyuleilei** [comment]
好的，感谢支持，我们会继续完善优化
