### ISSUE TITLE
数据看板能够统计当天现有数据么

### ISSUE THREAD

**Issue by reed0214** [a597873885/webfunny_event#7]
数据看板能够统计当天数据么,新增进行了今天的数据,但是数据看板当前统计数据依旧为0 
而且查询区间,起始日期不在查询范围内,例如现在查询26号到30号数据,26号未显示
![微信图片_20211130095812](https://user-images.githubusercontent.com/13160124/143971959-8b72fbe2-7782-4909-8d50-abc9a03dfc00.png)

**Comment by reed0214** [comment]
现在30天统计可以查看当天数据了,但是自定义范围的依旧不行
![微信截图_20211130113525](https://user-images.githubusercontent.com/13160124/143981377-f58e00b9-54af-4d81-a680-4af82e147f4e.png)

**Comment by yuyuleilei** [comment]
数据看板能够统计当天数据么,新增进行了今天的数据,但是数据看板当前统计数据依旧为0：这个默认是可以的，当天数据是一个小时分析一次，在每个小时零六的时候，统计分析出结果；

**Comment by yuyuleilei** [comment]
数据看板能够统计当天数据么,新增进行了今天的数据,但是数据看板当前统计数据依旧为0：这个默认是可以的，当天数据是一个小时分析一次，在每个小时零六的时候，统计分析出结果；

**Comment by yuyuleilei** [comment]
卡片自定义时间范围的查询，已经修复了，版本还没发布，等下个版本一起发布。

**Comment by reed0214** [comment]
好的,谢谢了,那就是新增数据,要在差不多一个小时后查看了就行了

**Comment by yuyuleilei** [comment]
方便加一下我们客服人员的微信(webfunny_2020)吗？我们拉个群，这样能快速解决你的问题
